name: build
on: [push]

env:
  VERSION_PREFIX: "0.7.0"

jobs:
    build:
        runs-on: windows-latest

        steps:

          - uses: Brightspace/third-party-actions@actions/checkout

          - name: Setup .NET
            uses:  Brightspace/third-party-actions@actions/setup-dotnet
            with:
                dotnet-version: |
                  3.1.x
                  5.0.x
                  6.0.x
                  8.0.x

          - name: Restore
            run: dotnet restore

          - name: Build
            run: dotnet build --configuration Release

          - name: Test
            run: dotnet test --configuration Release --no-build

          - name: Clean
            run: rm src/DotnetCIVersionProperties/bin/Release/*.nupkg

          - name: Version
            run: src/DotnetCIVersionProperties/bin/Release/netcoreapp3.1/DotnetCIVersionProperties.exe --output VersionInfo.props && cat VersionInfo.props

          - name: Rebuild
            run: dotnet build --configuration Release -target:Rebuild 

          - name: Copy *.nuget to dist/
            run: mkdir dist/ && cp src/DotnetCIVersionProperties/bin/Release/*.nupkg dist/

          - name: Archive dist/
            uses: actions/upload-artifact@v1
            with:
                name: dist
                path: dist/
